CREATE TABLE  IF NOT EXISTS TL_ARTICLES(ARTICLES_ID INT AUTO_INCREMENT  PRIMARY KEY, UUID VARCHAR2(250) NOT NULL, SLUG VARCHAR2(250), TITLE VARCHAR2(250), DESCRIPTION VARCHAR2(250), BODY VARCHAR2(250), CREATED_AT DATE, UPDATED_AT DATE, FAVORITED CHAR(1), FAVORITES_COUNT INT);

CREATE TABLE IF NOT EXISTS TL_TAGS(ID INT NOT NULL AUTO_INCREMENT, THEME VARCHAR2(50),ARTICLES_ID INT NOT NULL, PRIMARY KEY(ID)
,FOREIGN KEY (ARTICLES_ID) REFERENCES TL_ARTICLES(ARTICLES_ID));
